[context.staging.environment]
  APP_ENV = "staging"

[context.deploy-preview.environment]
  APP_ENV = "development"
  
[[redirects]]
  from = "/api"
  to = "https://v2.gpadcrew.com"
  status = 200
  force = true